routes/web.php
<?php
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('utama');
});

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

Route::middleware(['auth:sanctum', 'verified'])->get('/artikel', function () {
    return view('artikel');
})->name('artikel');

Route::post('/mandor/pasangproyek/detailproyek', function(){
    return view('mandor.pasangproyek.detailproyek');
});

Route::post('/mandor/carikuli/detailkuli', function(){
    return view('mandor.carikuli.detailkuli');
});


Route::get('/kuli/cariproyek/detail', '\App\Http\Controllers\Kuli\CariProyekController@detail');

Route::get('/kuli/cariproyek/daftar', '\App\Http\Controllers\Kuli\CariProyekController@apply');

Route::post('/batal', '\App\Http\Controllers\Kuli\CariProyekController@cancel');

Route::get('/legowo', '\App\Http\Controllers\Kuli\CariProyekController@legowo');

Route::get('/mandor/pasangproyek/detailproyek', '\App\Http\Controllers\Mandor\PasangProyekController@detail');

Route::get('/mandor/pasangproyek/seleksi', '\App\Http\Controllers\Mandor\PasangProyekController@seleksi');


Route::post('/ready', '\App\Http\Controllers\Kuli\AjukanDiriController@ready');

Route::post('/cancel', '\App\Http\Controllers\Kuli\AjukanDiriController@cancel');

Route::post('/terimapanggilan', '\App\Http\Controllers\Kuli\AjukanDiriController@accept');

Route::post('/tolakpanggilan', '\App\Http\Controllers\Kuli\AjukanDiriController@decline');

Route::post('/konfirmasi', '\App\Http\Controllers\Kuli\AjukanDiriController@confirm');


Route::post('/proyekbaru', '\App\Http\Controllers\Mandor\PasangProyekController@new');

Route::post('/hapusproyek', '\App\Http\Controllers\Mandor\PasangProyekController@delete');

Route::post('/terima', '\App\Http\Controllers\Mandor\PasangProyekController@terima');

Route::post('/tolak', '\App\Http\Controllers\Mandor\PasangProyekController@tolak');

Route::post('/mandor/carikuli/detailkuli', '\App\Http\Controllers\Mandor\CariKuliController@detail');

Route::post('/panggil', '\App\Http\Controllers\Mandor\CariKuliController@call');


Route::post('/selesai', '\App\Http\Controllers\Mandor\KuliAndaController@done');

Route::post('/batalselesai', '\App\Http\Controllers\Mandor\KuliAndaController@cancel');

Route::post('/batalpanggil', '\App\Http\Controllers\Mandor\KuliAndaController@cancelcall');

Route::post('/hapus', '\App\Http\Controllers\Mandor\KuliAndaController@delete');










Route::group(['middleware' => 'auth'], function () {
    // Route::group(['middleware' => 'role:admin', 'prefix' => 'admin', 'as' => 'admin.'], function() {
    //     Route::resource('lessons', \App\Http\Controllers\Students\LessonController::class);
    // });

    Route::group(['middleware' => 'role:kuli', 'prefix' => 'kuli', 'as' => 'kuli.'], function () {
        Route::resource('ajukandiri', \App\Http\Controllers\Kuli\AjukanDiriController::class);
    });

    Route::group(['middleware' => 'role:kuli', 'prefix' => 'kuli', 'as' => 'kuli.'], function () {
        Route::resource('cariproyek', \App\Http\Controllers\Kuli\CariProyekController::class);
    });

    Route::group(['middleware' => 'role:mandor', 'prefix' => 'mandor', 'as' => 'mandor.'], function () {
        Route::resource('carikuli', \App\Http\Controllers\Mandor\CariKuliController::class);
    });

    Route::group(['middleware' => 'role:mandor', 'prefix' => 'mandor', 'as' => 'mandor.'], function () {
        Route::resource('pasangproyek', \App\Http\Controllers\Mandor\PasangProyekController::class);
    });

    Route::group(['middleware' => 'role:mandor', 'prefix' => 'mandor', 'as' => 'mandor.'], function () {
        Route::resource('kulianda', \App\Http\Controllers\Mandor\KuliAndaController::class);
    });


    // Route::group(['middleware' => 'role:mandor', 'prefix' => 'mandor', 'as' => 'mandor.'], function() {
    //     Route::resource('users', \App\Http\Controllers\Admin\UserController::class);
    // });
});

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/artikel.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Artikel') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
                
                <div class="card">
                    <div class="card-body p-0">
                      
                        <div class="section-body">
                            <div class="row">
                                <div class="col-12 col-md-4 col-lg-4">
                                  <article class="article article-style-c">
                                    <div class="article-header">
                                      <div class="article-image" data-background="/stisla/assets/img/artikel/harianborongan.jpg" style="background-image: url(&quot;assets/img/news/img13.jpg&quot;);">
                                      </div>
                                    </div>
                                    <div class="article-details">
                                      <div class="article-category"><a href="#">Artikel</a> <div class="bullet"></div> <a href="#">5 Days</a></div>
                                      <div class="article-title">
                                        <h2><a href="#">Perbedaan Kuli Harian dan Borongan</a></h2>
                                      </div>
                                      <p>Sebuah artikel yang menjabarkan perbedaan istilah kuli harian dan borongan.</p>
                                      <div class="article-user">
                                        <img alt="image" src="/stisla/assets/img/avatar/avatar-1.png">
                                        <div class="article-user-details">
                                          <div class="user-detail-name">
                                            <a href="#">Bambang Wahyudi</a>
                                          </div>
                                          <div class="text-job">Mandor Profesional</div>
                                        </div>
                                      </div>
                                    </div>
                                  </article>
                                </div>
                                <div class="col-12 col-md-4 col-lg-4">
                                  <article class="article article-style-c">
                                    <div class="article-header">
                                      <div class="article-image" data-background="/stisla/assets/img/artikel/mandor_kabur.jpg" style="background-image: url(&quot;assets/img/news/img14.jpg&quot;);">
                                      </div>
                                    </div>
                                    <div class="article-details">
                                      <div class="article-category"><a href="#">Berita</a> <div class="bullet"></div> <a href="#">5 Days</a></div>
                                      <div class="article-title">
                                        <h2><a href="#">Mandor Bawa Kabur Uang Kuli</a></h2>
                                      </div>
                                      <p>Sebuah berita tentang seorang mandor yang membawa kabur uang kuli yang sudah bekerja keras.</p>
                                      <div class="article-user">
                                        <img alt="image" src="/stisla/assets/img/avatar/avatar-3.png">
                                        <div class="article-user-details">
                                          <div class="user-detail-name">
                                            <a href="#">Ahmad Mamad</a>
                                          </div>
                                          <div class="text-job">Tumbal Proyek</div>
                                        </div>
                                      </div>
                                    </div>
                                  </article>
                                </div>
                                <div class="col-12 col-md-4 col-lg-4">
                                  <article class="article article-style-c">
                                    <div class="article-header">
                                      <div class="article-image" data-background="/stisla/assets/img/artikel/kuli_jawa.jpg" style="background-image: url(&quot;assets/img/news/img01.jpg&quot;);">
                                      </div>
                                    </div>
                                    <div class="article-details">
                                      <div class="article-category"><a href="#">Artikel</a> <div class="bullet"></div> <a href="#">5 Days</a></div>
                                      <div class="article-title">
                                        <h2><a href="#">Tips Memilih Kuli Berkelas</a></h2>
                                      </div>
                                      <p>Sebuah artikel yang menjabarkan cara untuk memilih kuli yang profesional di bidangnya.</p>
                                      <div class="article-user">
                                        <img alt="image" src="/stisla/assets/img/avatar/avatar-2.png">
                                        <div class="article-user-details">
                                          <div class="user-detail-name">
                                            <a href="#">Babeh Resnu</a>
                                          </div>
                                          <div class="text-job">Pemborong</div>
                                        </div>
                                      </div>
                                    </div>
                                  </article>
                                </div>
                              </div>
                          </div>
                    </div>
                  </div>

            </div>
        </div>
    </div>
</x-app-layout>

resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    {{-- <div class="py-12"> --}}
    {{-- <div class="container"> --}}
    <div class="hero text-white bg-primary hero-bg-parallax">
        <div class="hero-inner">

            <div class="container">

                <h2>Halo, {{ auth()->user()->name }} !</h2>
                <p class="lead">Selamat datang di nguli.id, <br>Bersama kuli membangun negeri, Bersama mandor anti
                    kendor</p>
                @if (auth()->user()->role_id == '2')
                <p>Jadilah kuli yang profesional</p>
                @else
                <p>Jadilah mandor yang bertanggung jawab</p>
                @endif
                <div class="mt-4">
                    <a href="{{ route('profile.show') }}" class="btn btn-outline-white btn-lg btn-icon icon-left"><i
                            class="far fa-user"></i>
                        Lengkapi Akun</a>
                </div>
            </div>

            


        </div>
    </div>

    <div class="container p-5">


        <div class="card p-5 bg-info">
            {{-- <div class="card-header">
                  <h4>Mekanisme Layanan Nguli.id</h4>
                </div> --}}
            <div class="card-body">
                <div id="carouselExampleIndicators2" class="carousel slide" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#carouselExampleIndicators2" data-slide-to="0" class=""></li>
                        <li data-target="#carouselExampleIndicators2" data-slide-to="1" class="active"></li>
                        <li data-target="#carouselExampleIndicators2" data-slide-to="2" class=""></li>
                        <li data-target="#carouselExampleIndicators2" data-slide-to="3" class=""></li>
                    </ol>
                    <div class="carousel-inner">
                        <div class="carousel-item">
                            <img class="d-block w-100" src="assets/img/pengajuan_diri.png" alt="First slide">
                            <div class="carousel-caption d-none d-md-block">
                                <h5>Mekanisme Pengajuan Diri</h5>
                                <p>Kuli mengajukan diri pada halaman ajukan diri, mandor akan memilih kuli yang sesuai.</p>
                            </div>
                        </div>
                        <div class="carousel-item active">
                            <img class="d-block w-100" src="assets/img/pencarian_proyek.png" alt="Second slide">
                            <div class="carousel-caption d-none d-md-block">
                                <h5>Mekanisme Pencarian Proyek</h5>
                                <p>Kuli mencari proyek pada halaman cari proyek, setelah melamar kuli harus menunggu persetujuan
                                    dari mandor yang berwenang.
                                </p>
                            </div>
                        </div>
                        <div class="carousel-item">
                            <img class="d-block w-100" src="assets/img/pencarian_kuli.png" alt="Third slide">
                            <div class="carousel-caption d-none d-md-block">
                                <h5>Mekanisme Pencarian Kuli</h5>
                                <p>Mandor akan mencari kuli yang diinginkan pada halaman cari kuli, kuli akan mengkonfirmasi pemanggilan
                                    mandor tersebut.
                                </p>
                            </div>
                        </div>
                        <div class="carousel-item">
                            <img class="d-block w-100" src="assets/img/pemasangan_proyek.png" alt="Forth slide">
                            <div class="carousel-caption d-none d-md-block">
                                <h5>Mekanisme Pemasangan Proyek</h5>
                                <p>Mandor akan memasang proyek pada halaman pasang proyek, kuli akan melamar pada proyek tersebut,
                                    lalu mandor akan menyeleksi kuli yang mendaftar.
                                </p>
                            </div>
                        </div>

                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators2" role="button"
                        data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators2" role="button"
                        data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
            </div>
        </div>
    </div>
    {{-- </div> --}}
    {{-- </div> --}}

    {{-- <div class="container">
        <div class="card">
            <div class="card-header">
              <h4>Mekanisme Layanan Nguli.id</h4>
            </div>
            <div class="card-body">
              <div id="carouselExampleIndicators2" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                  <li data-target="#carouselExampleIndicators2" data-slide-to="0" class=""></li>
                  <li data-target="#carouselExampleIndicators2" data-slide-to="1" class="active"></li>
                  <li data-target="#carouselExampleIndicators2" data-slide-to="2" class=""></li>
                </ol>
                <div class="carousel-inner">
                  <div class="carousel-item">
                    <img class="d-block w-100" src="assets/img/gambar-tanah.jpg" alt="First slide">
                    <div class="carousel-caption d-none d-md-block">
                      <h5>Heading</h5>
                      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                      tempor incididunt ut labore et dolore magna aliqua.</p>
                    </div>
                  </div>
                  <div class="carousel-item active">
                    <img class="d-block w-100" src="assets/img/gambar-rumah.jpg" alt="Second slide">
                    <div class="carousel-caption d-none d-md-block">
                      <h5>Heading</h5>
                      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                      tempor incididunt ut labore et dolore magna aliqua.</p>
                    </div>
                  </div>
                  <div class="carousel-item">
                    <img class="d-block w-100" src="assets/img/gambar-kuli1.jpg" alt="Third slide">
                    <div class="carousel-caption d-none d-md-block">
                      <h5>Heading</h5>
                      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                      tempor incididunt ut labore et dolore magna aliqua.</p>
                    </div>
                  </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators2" role="button" data-slide="prev">
                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                  <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators2" role="button" data-slide="next">
                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                  <span class="sr-only">Next</span>
                </a>
              </div>
            </div>
          </div>
    </div> --}}

    {{-- <div class="py-12"> --}}
    {{-- <div class="container p-3">
        <div class="card">
            <div class="card-header">
                <h4>Mekanisme Pengajuan Diri</h4>
            </div>
            <div class="card-body">
                <div class="row mt-4">
                    <div class="col-12 col-lg-8 offset-lg-2">
                        <div class="wizard-steps">
                            <div class="wizard-step wizard-step-active">
                                <div class="wizard-step-icon">
                                    <i class="fas fa-address-book"></i>
                                </div>
                                <div class="wizard-step-label">
                                    Kuli Mengajukan Diri
                                </div>
                            </div>
                            <div class="wizard-step wizard-step-active">
                                <div class="wizard-step-icon">
                                    <i class="fas fa-search"></i>
                                </div>
                                <div class="wizard-step-label">
                                    Mandor Mencari Kuli
                                </div>
                            </div>
                            <div class="wizard-step wizard-step-active">
                                <div class="wizard-step-icon">
                                    <i class="fas fa-phone"></i>
                                </div>
                                <div class="wizard-step-label">
                                    Mandor Memanggil Kuli
                                </div>
                            </div>
                            <div class="wizard-step wizard-step-success">
                                <div class="wizard-step-icon">
                                    <i class="fas fa-check"></i>
                                </div>
                                <div class="wizard-step-label">
                                    Siap Kerja
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div> --}}
    {{-- </div> --}}

    {{-- <div class="py-12"> --}}
    {{-- <div class="container">
        <div class="card">
            <div class="card-header">
                <h4>Mekanisme Pemasangan Proyek</h4>
            </div>
            <div class="card-body">
                <div class="row mt-4">
                    <div class="col-12 col-lg-8 offset-lg-2">
                        <div class="wizard-steps">
                            <div class="wizard-step wizard-step-active">
                                <div class="wizard-step-icon">
                                    <i class="fas fa-fax"></i>
                                </div>
                                <div class="wizard-step-label">
                                    Mandor Memasang Proyek
                                </div>
                            </div>
                            <div class="wizard-step wizard-step-active">
                                <div class="wizard-step-icon">
                                    <i class="fas fa-search"></i>
                                </div>
                                <div class="wizard-step-label">
                                    Kuli Mencari Proyek
                                </div>
                            </div>
                            <div class="wizard-step wizard-step-active">
                                <div class="wizard-step-icon">
                                    <i class="fas fa-handshake"></i>
                                </div>
                                <div class="wizard-step-label">
                                    Mandor Menerima Kuli
                                </div>
                            </div>
                            <div class="wizard-step wizard-step-success">
                                <div class="wizard-step-icon">
                                    <i class="fas fa-check"></i>
                                </div>
                                <div class="wizard-step-label">
                                    Siap Kerja
                                </div>
                            </div>


                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div> --}}
    {{-- </div> --}}
</x-app-layout>

resources/views/dashboard2.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
                <x-jet-welcome />
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/policy.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-jet-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                {!! $policy !!}
            </div>
        </div>
    </div>
</x-guest-layout>

resources/views/terms.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-jet-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                {!! $terms !!}
            </div>
        </div>
    </div>
</x-guest-layout>